spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - path = /customers/**

        - id: r2
          uri: http://localhost:8083
          predicates:
            - path = /products/**
